name: yandex_mapkit
description: A Flutter plugin for integrating Yandex.MapKit in Android and iOS applications.
version: 4.3.0
homepage: https://github.com/Unact/yandex_mapkit

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.3"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.30
  equatable: ^2.0.7
  collection: any
  flutter:
    sdk: flutter

dev_dependencies:
  meykuless_lint_rules:
    git:
      url: https://github.com/DaniilPavlov/meykuless_lint_rules.git
      ref: 190e704f0bcedbe8558d7e4f11c022dcaf60072e

flutter:
  plugin:
    platforms:
      android:
        package: com.unact.yandexmapkit
        pluginClass: YandexMapkitPlugin
      ios:
        pluginClass: YandexMapkitPlugin
