name: yandex_mapkit
description: A Flutter plugin for integrating Yandex.MapKit in Android and iOS applications.
version: 4.2.0
homepage: https://github.com/Unact/yandex_mapkit

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.3"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.30
  equatable: ^2.0.7
  collection: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.unact.yandexmapkit
        pluginClass: YandexMapkitPlugin
      ios:
        pluginClass: YandexMapkitPlugin
